/// Flutter Rust Bridge integration.
///
/// This module provides the FFI layer between Dart and the
/// seal-core Rust crate. Bindings are auto-generated by
/// flutter_rust_bridge_codegen during build.
///
/// Usage:
/// ```dart
/// import 'package:seal_dart/src/core/rust_bridge.dart';
/// ```

// The auto-generated bridge file will be at:
//   lib/src/core/frb_generated.dart
//
// To regenerate:
//   flutter_rust_bridge_codegen generate
//
// For now this is a placeholder. The actual bridge code
// is generated from crates/seal-core/src/*.rs

class RustBridge {
  static bool _initialized = false;

  /// Initialize the Rust FFI bridge. Must be called once at app startup.
  static Future<void> init() async {
    if (_initialized) return;
    // TODO: Call auto-generated init from flutter_rust_bridge
    // await RustLib.init();
    _initialized = true;
  }
}
